### ISSUE TITLE
Is it no more working of i missunderstod something ?

### ISSUE THREAD

**Issue by Nevrdid** [alexpharris/MonkeyMod#2]
Hey, i switched to your new release but it doesn't count me any word as beaten. It continue to always show me the same list of words.
Is it in progress or i miss something ?
I changed the treshold to 70 in case it were because i type any word faster than 50 wpm but that changed nothing.
I well setup a list of words and the remaining words on the left if right. Also, is it corect that we only have to type tabulation once on result screen to continue ?
Thanks.

**Comment by alexpharris** [comment]
@Nevrdid Sorry, I didn't know anyone else was even using this!

I think the version you were using probably required that all words be typed perfectly, basically like master mode even if you were using normal or expert. Would that explain the problem?

I just pushed a bunch of changes. I haven't been able to test them out and I think I might have introduced some bugs, but I'm curious to know if it solves your problem.

I was also glad to hear in #1 that this has been helpful for you! I don't know if you've seen it, but I added the ability to save custom lists on the results page:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/99990705/155400669-f76ddb14-71cb-40ef-a896-e9d560210556.png">

Sorry this is changing so much! This is really just a pet project and I didn't realize anyone else was using it.

**Comment by Nevrdid** [comment]
I upated to 0.5 and succefully made it work once i understood i must enable and setup custom mode before start game :)
I got some kind of infinite loading before ^^'
Don't worry about the big changes, as it look really efficient  to train this way. :100:
